world_address = "0x0048c5cd2e25b2758f4d52e8fd760c5fca61fb0b42f223a30c66a08029c6565b"
rpc = "https://api.cartridge.gg/x/starknet/mainnet"
explorer = false

[events]
raw = true

[sql]
historical = [
    "ponzi_land-AddressAuthorizedEvent",
    "ponzi_land-AddressRemovedEvent",

    "ponzi_land-AuctionFinishedEvent",
    "ponzi_land-LandBoughtEvent",
    "ponzi_land-LandNukedEvent",

    "ponzi_land-NewAuctionEvent",
    "ponzi_land-RemainingStakeEvent",

    "ponzi_land-VerifierUpdatedEvent",
]


[indexing]
contracts = [
    "erc20:0x05735fa6be5dd248350866644c0a137e571f9d637bb4db6532ddd63a95854b58", # eSTRK
    "erc20:0x05735fa6be5dd248350866644c0a137e571f9d637bb4db6532ddd63a95854b58", # ePAPER
    "erc20:0x04b66d22d3001daad50fb853c0c1cb3b96d1745acb295bae4a6d54b29125ed09", # eLORDS
    "erc20:0x01920ef3c5e765454dd3f6aeb5420ef524830e0b5f9a95ec2e1b9ee2073a16d1", # eBROTHER
    "erc20:0x079aba4c89e9cc3495318d2479fe93601e1188ff5d9a8823e3dc736d74bb437f", # ePAL
    "erc20:0x038217779933c147320af3239e2dd098312e3074e0898001c79939c2e676fe8c", # eETH
    "erc20:0x04c090a1a34a3ba423e63a498ce23de7c7a4f0f1a8128fa768a09738606cbb9e", # eBTC
]
