name: Client - Cloudflare Deploy (sepolia)

on:
  push:
    branches:
      - "main"
      - "target/*"
  # Cloudflare handles preview environments pretty well:
  pull_request:
    branches:
      - "main"
      - "target/*"

permissions:
  contents: read
  deployments: write
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  packages: read

jobs:
  slot-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - id: setup-dojo
        uses: runelabsxyz/setup-dojo@main
        with:
          version: "v1.0.12"

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          registry-url: "https://npm.pkg.github.com/"
          scope: "@runelabsxyz"

      - name: Install dependencies
        working-directory: ./client
        env:
          BUN_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bun install --frozen-lockfile

      - name: Build frontend for sepolia
        run: bun run build:sepolia
        working-directory: ./client
        env:
          LAYERSWAP_TOKEN: ${{ secrets.LAYERSWAP_TOKEN }}
          BYPASS_TOKEN: ${{ secrets.BYPASS_TOKEN }}
          # Force the auto bundler to prepare for cloudflare (otherwise it does weird things)
          CF_PAGES: "1"

      - name: Deploy to Cloudflare Pages
        uses: andykenward/github-actions-cloudflare-pages@v2.3.2
        id: pages
        with:
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare-project-name: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
          directory: ./client/.svelte-kit/cloudflare
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-environment: PonziLand ${{ (github.ref == 'refs/heads/main' && '(Production)') || '(Preview)' }}
